name: CI

on:
  push:
  schedule:
  - cron: '50 7 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Deploy
      if: startsWith(github.ref, 'refs/tags/v')
      run: make release
      
